class ErrorCodes:

    SELF_ASSIGNMENT_FORBIDDEN = "SELF_ASSIGNMENT_FORBIDDEN"
    SELF_MODIFICATION_FORBIDDEN = "SELF_MODIFICATION_FORBIDDEN"
    UNAUTHORIZED_LOCATION = "UNAUTHORIZED_LOCATION"

    SESSION_INVALID = "SESSION_INVALID"

    PRIMARY_LOCATION_EXISTS = "PRIMARY_LOCATION_EXISTS"

    ALREADY_RESIGNED = "ALREADY_RESIGNED"
    CREDENTIALS_EXPIRED = "CREDENTIALS_EXPIRED"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    NIK_DUPLICATE = "NIK_DUPLICATE"
    STAFF_ALREADY_ASSIGNED = "STAFF_ALREADY_ASSIGNED"

    CANNOT_REMOVE_PRIMARY = "CANNOT_REMOVE_PRIMARY"
    UNDO_EXPIRED = "UNDO_EXPIRED"
    UNDO_TOKEN_INVALID = "UNDO_TOKEN_INVALID"

    SAME_LOCATION = "SAME_LOCATION"
